### ISSUE TITLE
Un peu de doc dans le Readme

### ISSUE THREAD

**Issue by Grahack** [AlainBusser/Sophus#3]
Salut,
Serait-il possible d’ajouter un peu de doc dans le Readme, par exemple une liste exhaustive des mots-clef et quelques exemples ?
Sinon indiquer un endroit où on peut trouver ça.
Merci.

**Comment by AlainBusser** [comment]
normalement c'est fait. Basiquement on clique sur le mot "syntaxe" en bleu pour rendre visible la liste des instructions. Mais pour m'en souvenir je regarde le fichier "sophus.coffee" qui définit les instructions (instruction = fonction dans Sophus)

**Comment by Grahack** [comment]
Je parlais du Readme de ce dépôt.
Comme ça, en arrivant sur https://github.com/AlainBusser/Sophus/ on a tout.

**Comment by rodeofly** [comment]
Le readme m'a l'air à jour maintenant, on peut fermer la discussion !

**Comment by Grahack** [comment]
Derniers point flou:

> La syntaxe est déductible des fichiers coffee
- Peut-on avoir des détails dans le readme?
- Pourriez-vous ajouter quelques exemples dans le readme, ou un lien vers des exemples?

Merci.
